pagina/urls.py
#começando as páginas - url - view - template

from django.contrib import admin
from django.urls import path, include, reverse_lazy
from .views import *
from django.contrib.auth import views
from django.contrib.auth.views import PasswordResetConfirmView
from .tasks import *



app_name = 'pagina'

urlpatterns = [
     path('', Homepage.as_view(), name='homepage'),
     path('navbar', navbar.as_view(), name='navbar'),
     path("Notificacoes_dos_usuarios/", Notificacoes_dos_usuarios.as_view(), name='Notificacoes_dos_usuarios'),
     path("Notificacoes_dos_usuarios/<str:task_id>/", Notificacoes_dos_usuarios.as_view(), name='status_notificacoes'),
     # path('teste', teste, name='teste'),
     # path('check_task_status/<str:task_id>/', check_task_status, name='check_task_status'),
     path('Clery_teste', Clery_teste.as_view(), name='Clery_teste'),
     path('marcar_notificacao_lida/<str:notification_id>/', marcar_notificacao_lida, name='marcar_notificacao_lida'),
]

site_raul/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pagina.urls'))
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pagina/models.py
from django.db import models

# Create your models here.

pagina/views.py
from django.shortcuts import render
from django.views.generic import TemplateView, FormView, UpdateView, ListView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views import View
from django.http import HttpResponse
from .tasks import teste_func, notificar
from django.http import JsonResponse
from celery.result import AsyncResult
from django.views.decorators.csrf import csrf_exempt
from django_celery_results.models import TaskResult
from django.db.models import Sum, Value, F
import json
from .notifications import get_unread_notifications
from notifications.models import Notification
from django.views.decorators.http import require_http_methods


class Homepage(TemplateView):
    template_name = 'homegeral.html'
    
class navbar(TemplateView):
    template_name = 'navbar.html'


class Clery_teste(TemplateView):
    template_name = 'celery_teste.html'


# @csrf_exempt
class Notificacoes_dos_usuarios(View):

    def post(self, request):
        
        task_result = teste_func.delay()
        return JsonResponse({'task_id': task_result.id})

    def get(self, request, task_id=None):
        task_result = TaskResult.objects.filter(task_id=task_id).values('task_id').annotate(status = F('status'))
        print(task_result)
        if task_result.exists():
            task_result = {item['task_id']: item['status'] for item in task_result}
            print(task_result)
            response_data = {'status': task_result[task_id]}
            task = TaskResult.objects.get(task_id = task_id)
            
            if response_data['status'] == "SUCCESS":
                result = task.result
                nome_tarefa = task.task_name
                result = eval(result.replace("'",'"'))
                response_data['result'] = result['itens_atualizados']
                response_data['tarefa'] = nome_tarefa
                notificar(request.user, response_data)
            
            return JsonResponse(response_data)
        
        return JsonResponse({'error': 'Task ID não fornecido'})


def marcar_notificacao_lida(request, notification_id):
    notificacao = Notification.objects.get(id=notification_id)

    if notificacao.recipient == request.user:
        notificacao.mark_as_read()

        return JsonResponse({'message': 'Notificação marcada como lida com sucesso.'})
    else:

        return JsonResponse({'error': 'Você não tem permissão para marcar esta notificação como lida.'}, status=403)

pagina/templates/base.html
{% load static %}
<html>
  <title>{% block titulo %} {% endblock %}</title>
  {% block head %}
  <head>
    <link rel="icon" href="#" type="image/x-icon" />
    <meta charset="utf-8" />
    {% comment %}
    <link rel="stylesheet" href="{% static 'css/css.css' %}" />
    {% endcomment %} {% comment %}
    <link rel="stylesheet" href="{% static 'css/formatacao_padrao.css' %}" />
    {% endcomment %}
    <script src="https://cdn.tailwindcss.com"></script>
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM"
      crossorigin="anonymous"
    />
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <link
      rel="stylesheet"
      type="text/css"
      href="https://cdn.datatables.net/v/bs5/dt-1.13.5/datatables.min.css"
    />
    <link
      rel="stylesheet"
      type="text/css"
      href="https://cdn.datatables.net/v/bs5/dt-1.11.4/datatables.min.css"
    />
    <script src="https://cdn.datatables.net/v/bs5/dt-1.11.4/datatables.min.js"></script>
  </head>
  {% endblock %}

  <body
    class="bg-gradient-to-b from-gray-500 to-gray-200 text-gray-100 font-primary"
  >
    {% include 'navbar.html' %} 
    {% block content %} 

    {% endblock %}

    <script
      type="module"
      src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.esm.js"
    ></script>
    <script
      nomodule
      src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.js"
    ></script>
  </body>

  <footer class="h-fit bg-grey-400 px-4 rounded-lg shadow m-1 dark:bg-gray-800">
    <ul class="flex justify-between items-center">
      <li>&copy; 2023</li>
      <li>Feito com Python (Django)</li>
      <li>Auto Equip Versão 1.2</li>
    </ul>
  </footer>
</html>

pagina/templates/celery_teste.html
{% extends 'base.html' %}
{% load static %}

{% block titulo %}
Portal Auto Equip
{% endblock  %}

{% block head %}
<meta name="viewport" content="width=device-width, user-scalable=yes, initial-scale=1.0, maximum-scale=10, minimum-scale=1.0">
{% endblock %}

{% block content %}
<link rel="stylesheet" href="{% static 'css/baloes_msgm.css' %}" />
<section style="min-height: 100vh;">
    </br>
    <div>
        <h2 class="balao-mensagem gradient-animation" id="notification">Olá {{ user.username }}, bem vindo ao portal! Aqui temos algumas informações gerais.</h2>
    </div>

    <form id="submit-form" class="space-x-2 flex flex-wrap mt-2 bg-gray-700 rounded-md">
        {% csrf_token %}
        <select class="bg-black" name="filial_autoequip_todos">
            <option value="">Selecione a Filial</option>
            <option value="SC">SC</option>
            <option value="SP">SP</option>
        </select>
        <button type="button" id="submit-btn" class="bg-red-600 text-black my-1 mx-1 px-2 font-bold rounded-md">Atualizar todos</button>
    </form>

    

    {% if notificacao %}
        {{ notificacao}}
    {% endif %}
</section>

<script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
<script>

    // Aqui eu preciso do token csrf para autenticar o fomulário (função que irá enviar a solicitação) usando ajax a eu chamo a classe Notificaçoes do usuários
    // e uso o método post para enviar a tarefa que precisa ser feita passando o task id que irá ser usado na função de checkTaskStatus, a função checkTaskStatus usa a mesma classe porém
    // a url é diferente pois leva a task id junto e o método dela é GET pois vai buscar no banco o status da tarefa!
    $(document).ready(function () {
        var csrfToken = $('input[name=csrfmiddlewaretoken]').val();
        var notificationDisplayed = false;
        
        $('#submit-btn').click(function () {
            $.ajax({
                url: '{% url "pagina:Notificacoes_dos_usuarios" %}',
                type: 'POST',
                dataType: 'json',
                headers: {'X-CSRFToken': csrfToken}, 
                success: function (data) {
                    checkTaskStatus(data.task_id);
               },
            });
        });
    
        function checkTaskStatus(taskId) {
            $.ajax({
                url: '/Notificacoes_dos_usuarios/' + taskId + '/',
                type: 'GET',
                dataType: 'json',
                success: function (data) {
                    if (data.status === 'SUCCESS' && !notificationDisplayed) {
                        notificationDisplayed = true;
                    } else if (!notificationDisplayed) {
                        setTimeout(function () {
                            checkTaskStatus(taskId);
                        }, 10000);  // Intervalo de 10 segundo para verificar se a tarefa foi concluída
                    }
                },
            });
        }
    });
</script>

{% endblock %}

pagina/templates/homegeral.html
{% extends 'base.html' %}
{% load static %}

{% block titulo %}
Portal Auto Equip
{% endblock  %}

{% block 'head' %}
<meta name="viewport" content="width=device-width, user-scalable=yes, initial-scale=1.0, maximum-scale=10, minimum-scale=1.0">
{% endblock%}

{% block content %}
<link rel="stylesheet" href="{% static 'css/baloes_msgm.css' %}" />
<section style="min-height: 100vh;">
</br>
<div>
    <h2 class="balao-mensagem gradient-animation">Olá {{ user.username }}, bem vindo ao portal! Aqui temos algumas informações gerais.</h2>
</div>

<div class="carrosel teste">
    <ul>

        <li>
            <div class="div-metas">
                <h1>Visão Geral dos Marketplaces</h1>

                <div class="two-columns">
                    <div class="left-column">
                        <h1>Metas atingidas:</h1>
                        <div class="tabela-400-altura">
                            <table>
                                <thead>
                                    <tr>
                                        <th scope="col">Marketplaces</th>
                                        <th scope="col">Faturamento</th>
                                        <th scope="col">Meta</th>
                                        <th scope="col"> % Batida da meta</th>
                                        <th scope="col">Filial</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <tr>
                                        <td>       
                                            <div class="celula-tabela-com-imagem">
                                                <h2>Mercado Livre</h2>
                                                <img src="{% static 'images/logomeli.png' %}" width='55' height='55'>
                                            </div>
                                        </td>
                                        <td><span id="fat_meli_sp">fat meli</span></td>
                                        <td><span id="meta_meli_sp">meta meli</span></td>
                                        <td><span id="meta_atingida_meli_sp">% meta</span></td>
                                        <td>SP</td>
                                    </tr>
        
                                    <tr>
                                        <td>       
                                            <div class="celula-tabela-com-imagem">
                                            <h2>Loja Integrada</h2>
                                            <img src="{% static 'images/logoli.png' %}" width='55' height='55'>
                                        </div>
                                    </td>
                                    <td><span id="fat_li">fat li</span></td>
                                    <td><span id="meta_li">meta li</span></td>
                                    <td><span id="meta_atingida_li">% meta</span></td>
                                    <td>SP/SC</td>
                                    </tr>
        
                                    <tr>
                                        <td>       
                                            <div class="celula-tabela-com-imagem">
                                            <h2>Magazine Luiza</h2>
                                            <img src="{% static 'images/logomagalu.png' %}" width='55' height='55'>
                                        </div>
                                    </td>
                                    <td><span id="fat_magalu_sp">fat magalu</span></td>
                                    <td><span id="meta_magalu_sp">meta magalu</span></td>
                                    <td><span id="meta_atingida_magalu_sp">% meta</span></td>
                                    <td>SP</td>
                                    </tr>
        
                                    <tr>
                                        <td>       
                                            <div class="celula-tabela-com-imagem">
                                            <h2>Amazon</h2>
                                            <img src="{% static 'images/logoamazon.png' %}" width='55' height='55'>
                                        </div>
                                    </td>
                                    <td><span id="fat_amazon_sp">fat Amazon</span></td>
                                    <td><span id="meta_amazon_sp">meta amazon</span></td>
                                    <td><span id="meta_atingida_amazon_sp">% meta</span></td>
                                    <td>SP</td>
                                    </tr>
        
                                    <tr>
                                        <td>       
                                            <div class="celula-tabela-com-imagem">
                                            <h2>Americanas</h2>
                                            <img src="{% static 'images/logoamericanas.png' %}" width='55' height='55'>
                                        </div>
                                    </td>
                                    <td><span id="fat_americanas_sp">fat Americanas</span></td>
                                    <td><span id="meta_americanas_sp">meta Americanas</span></td>
                                    <td><span id="meta_atingida_americanas_sp">% meta</span></td>
                                    <td>SP</td>
                                    </tr>
        
                                    <tr>
                                        <td>       
                                            <div class="celula-tabela-com-imagem">
                                            <h2>Shopee</h2>
                                            <img src="{% static 'images/logoshopee.png' %}" width='55' height='55'>
                                        </div>
                                    </td>
                                    <td><span id="fat_shopee_sp">fat Shopee</span></td>
                                    <td><span id="meta_shopee_sp">meta Shopee</span></td>
                                    <td><span id="meta_atingida_shopee_sp">% Shopee</span></td>
                                    <td>SP</td>
                                    </tr>
        
                                    <td>       
                                        <div class="celula-tabela-com-imagem">
                                        <h2>Mercado Livre</h2>
                                        <img src="{% static 'images/logomeli.png' %}" width='55' height='55'>
                                    </div>
                                </td>
                                <td><span id="fat_meli_sp">fat meli</span></td>
                                <td><span id="meta_meli_sp">meta meli</span></td>
                                <td><span id="meta_atingida_meli_sp">% meta</span></td>
                                <td>SP</td>
                            </tr>
        
                            <tr>
                                <td>       
                                    <div class="celula-tabela-com-imagem">
                                        <h2>Magazine Luiza</h2>
                                        <img src="{% static 'images/logomagalu.png' %}" width='55' height='55'>
                                    </div>
                                </td>
                                <td><span id="fat_magalu_sp">fat magalu</span></td>
                                <td><span id="meta_magalu_sp">meta magalu</span></td>
                                <td><span id="meta_atingida_magalu_sp">% meta</span></td>
                                <td>SP</td>
                            </tr>
        
                            <tr>
                                <td>       
                                    <div class="celula-tabela-com-imagem">
                                        <h2>Amazon</h2>
                                        <img src="{% static 'images/logoamazon.png' %}" width='55' height='55'>
                                    </div>
                                </td>
                                <td><span id="fat_amazon_sp">fat Amazon</span></td>
                                <td><span id="meta_amazon_sp">meta amazon</span></td>
                                <td><span id="meta_atingida_amazon_sp">% meta</span></td>
                                <td>SP</td>
                            </tr>
        
                            <tr>
                                <td>       
                                    <div class="celula-tabela-com-imagem">
                                        <h2>Americanas</h2>
                                        <img src="{% static 'images/logoamericanas.png' %}" width='55' height='55'>
                                    </div>
                                </td>
                                <td><span id="fat_americanas_sp">fat Americanas</span></td>
                                <td><span id="meta_americanas_sp">meta Americanas</span></td>
                                <td><span id="meta_atingida_americanas_sp">% meta</span></td>
                                <td>SP</td>
                            </tr>
        
                            <tr>
                                <td>       
                                    <div class="celula-tabela-com-imagem">
                                        <h2>Shopee</h2>
                                        <img src="{% static 'images/logoshopee.png' %}" width='55' height='55'>
                                    </div>
                                </td>
                                <td><span id="fat_shopee_sp">fat Shopee</span></td>
                                <td><span id="meta_shopee_sp">meta Shopee</span></td>
                                <td><span id="meta_atingida_shopee_sp">% Shopee</span></td>
                                <td>SP</td>
                            </tr>
        
                                </tbody>
                            </table>
                        </div>
                    </div>

                    <div class="right-column">
                        <div class="half-container">
                            <div class="half top-half">
                                <h1>São Paulo</h1>
                                <!-- Conteúdo da metade superior aqui -->
                            </div>
        
                            <div class="half bottom-half">
                                <h1>Santa Catarina</h1>
                                <!-- Conteúdo da metade inferior aqui -->
                            </div>
                        </div>
                    </div>
                    
                </div>

            </div>
            


        </li>

        <li>
            <div class="div-metas">
                <h1>Alguns dos produtos mais vendidos, não deixe faltar!</h1>

                <div class="two-columns">
                    <div class="right-column">
                        <div class="half-container">
                            <div class="half half-produtos">
                                <h1>São Paulo</h1>
                                <!-- Conteúdo da metade superior aqui -->
                            </div>
        
                            <div class="half half-produtos">
                                <h1>Santa Catarina</h1>
                                <!-- Conteúdo da metade inferior aqui -->
                            </div>
                        </div>
                    </div>
                </div>

            </div>

        </li>

        <li>
            <div class="div-metas">
                <h1>Próxima datas comemorativas, fique atento!</h1>

                <div class="two-columns">
                    <div class="right-column">
                        <div class="half-container">
                            <div class="half half-produtos">
                                <h1>São Paulo</h1>
                                <!-- Conteúdo da metade superior aqui -->
                            </div>
        
                            <div class="half half-produtos">
                                <h1>Santa Catarina</h1>
                                <!-- Conteúdo da metade inferior aqui -->
                            </div>
                        </div>
                    </div>
                </div>
              
            </div>
        </li>

    </ul>
</div>


<script>

</script>

</section>
{% endblock  %}

pagina/templates/navbar.html
{% load static %}
<link rel="stylesheet" href="{% static 'css/navbar.css' %}" />
<nav data-pause="True">
  <a class="logo" href="/"><img src="{% static 'images/logoredonda.png' %}" height="50" width="50"/>Portal Auto Equip</a>
  <div class="notifications-icon-nav" id="notifications-icon-nav">
    <svg xmlns="http://www.w3.org/2000/svg" width="27" height="27" fill="white" class="bi bi-bell-fill" viewBox="0 0 16 16">
      <path d="M8 16a2 2 0 0 0 2-2H6a2 2 0 0 0 2 2zm.995-14.901a1 1 0 1 0-1.99 0A5.002 5.002 0 0 0 3 6c0 1.098-.5 6-2 7h14c-1.5-1-2-5.902-2-7 0-2.42-1.72-4.44-4.005-4.901z"/>
    </svg>
    {% if qnt_notificacoes %}
      <div class="icone-notificacao-n-lida" id="qnt_notificacao_n_lida" value="{{ qnt_notificacoes }}">{{ qnt_notificacoes }}</div>
    {% endif %}
  </div>
  
  <div class="notifications-list-nav" id="notifications-list-nav">
    <ul class="nav-list-notificacao">
      {% if unread_notifications %}
      {% for notificacao in unread_notifications %}
        <li> Tarefa: {{ notificacao.tarefa }} </br> status: {{ notificacao.status }} </br> resultado: {{ notificacao.resultado }}  
            <button class="marcar-lida-btn" data-notificacao-id="{{ notificacao.id_notificacao }}">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="white" class="bi bi-check-square" viewBox="0 0 16 16">
                <path d="M14 1a1 1 0 0 1 1 1v12a1 1 0 0 1-1 1H2a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1zM2 0a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2z"/>
                <path d="M10.97 4.97a.75.75 0 0 1 1.071 1.05l-3.992 4.99a.75.75 0 0 1-1.08.02L4.324 8.384a.75.75 0 1 1 1.06-1.06l2.094 2.093 3.473-4.425a.235.235 0 0 1 .02-.022z"/>
              </svg>
          </button>
        </li>
      {% endfor %}
      {% else %}
      <li>Nenhuma notificacao.</li>
      {% endif %}
    </ul>
  </div>
  


  <div class="mobile-menu">
    <div class="line1"></div>
    <div class="line2"></div>
    <div class="line3"></div>


    <ul class="nav-list">
      <li><a href="#">Início</a></li>
      <li><a href="{% url 'pagina:InformacoesFulfillment' %}">Fulfillment Mercado Livre</a></li>
      <li><a href="{% url 'pagina:PosVendas' %}">Pós Vendas</a></li>
      <li><a href="{% url 'pagina:Cadastro_metas_marketplaces' %}">Cadastro de Metas</a></li>
      <li><a href="{% url 'pagina:MetasComercial' %}">Metas</a></li>
      <li><a href="{% url 'pagina:Compras' %}">Compras</a></li>
      <li><a href="{% url 'pagina:CurvaABC' %}">Curva ABC</a></li>
      <li><a href="{% url 'pagina:dashboards' %}">Dashboards</a></li>
      <li><a href="{% url 'pagina:precificacao' %}">Precificação</a></li>
      <li><a href="{% url 'pagina:editarperfil' user.pk %}">Editar Perfil</a></li>
      <li><a href="{% url 'pagina:logout' %}">Logout</a></li>
    </ul>
  </div>
</nav>

<script src="{% static "js/navbar.js" %}"></script>
<script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
<script>
  // Adicione este script para manipular o clique no botão e chamar a função Ajax
  document.addEventListener('DOMContentLoaded', function () {
    var buttons = document.querySelectorAll('.marcar-lida-btn');

    buttons.forEach(function (button) {
      button.addEventListener('click', function () {
        var notificacaoId = this.getAttribute('data-notificacao-id');
        console.log(notificacaoId)

        // Chama a função Ajax para marcar a notificação como lida
        marcarNotificacaoLida(notificacaoId, button);
      });
    });

    function marcarNotificacaoLida(notificacaoId, button) {
      // Use Ajax para chamar sua view Django que marca a notificação como lida
      // Você pode usar bibliotecas como jQuery ou o fetch API para isso
      console.log(notificacaoId)
      // Exemplo usando fetch API
      fetch('/marcar_notificacao_lida/' + notificacaoId + '/')
        .then(response => response.json())
        .then(data => {
          // Lógica para lidar com a resposta do servidor (pode ser uma mensagem de sucesso, erro, etc.)
          var qntElement = document.getElementById('qnt_notificacao_n_lida');
          var notificaoes_iniciais = parseFloat(qntElement.textContent)
          console.log(notificaoes_iniciais);

          if (data.message == "Notificação marcada como lida com sucesso.") {
            var listItem = button.closest('li');
            if (listItem) {
              listItem.remove();
              notificaoes_iniciais_finais = notificaoes_iniciais - 1;

              var qntElement = document.getElementById('qnt_notificacao_n_lida');
              if (qntElement) {
                qntElement.textContent = notificaoes_iniciais_finais;
          
                // Remova o elemento se não houver mais notificações não lidas
                if (notificaoes_iniciais_finais === 0) {
                  qntElement.remove();
                }
              }
            }
          }
        })
        .catch(error => {
          console.error('Erro ao chamar a API:', error);
        });
    }
  });
</script>

pagina/templates/teste.html
sdadsadadadsa